# Indicates the latest recommended release version
DOWNLOAD_VERSION: 0.4.23

# Place an alert using one of these classes:
# error (big problem!)
# success (we've fixed it!)
# info (something important is happening)
ALERT_CLASS: success
# Add the text of the alert in here
ALERT: Here is some alert text

# The list of supported languages
langs:
- langcode: fr
  langtext: Fran√ßais
- langcode: en
  langtext: English

# Only applies to WEBrick
safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
    
aliases:
  jimburton: Jim Burton
  garyrowe: Gary Rowe
  timmolter: Tim Molter
  saivanncarigan: Saivann Carigan

